In [1]:
import numpy as np

a = np.array([[1,3],[2,-5]])
b = np.array([[10],[-2]])
print(np.linalg.solve(a,b))



[[4.]
 [2.]]


In [2]:
a1 = np.array([[1,2,4],[0,1,5],[-2,-4,-3]])
b1 = np.array([[-2],[2],[9]])
a2 = np.array([[1,2,1],[-3,-1,2],[0,5,3]])
b2 = np.array([[0],[1],[-1]])
print(f"Ex: 11: \n{np.linalg.solve(a1,b1)}\n")
print(f"Ex 12: \n{np.linalg.solve(a2,b2)}\n")

Ex: 11: 
[[-0.]
 [-3.]
 [ 1.]]

Ex 12: 
[[ 0.6]
 [-0.8]
 [ 1. ]]



In [3]:
l1 = [2,4,3]
l2 = [5,6,4]
def sum_list(l1: list, l2: list) -> list:
    l1.reverse()
    l2.reverse()
    s = str(int("".join(map(str, l1))) + int("".join(map(str, l2))))
    l = [int(s[x]) for x in range(len(s))]
    return l

print(sum_list(l1,l2))

[8, 0, 7]


In [4]:
nums = [2,5,1,3,4,7]
n = 3
ans = [x for i in range(n) for x in (nums[i], nums[i+n])]
print(ans)





[2, 3, 5, 4, 1, 7]


In [5]:
nums = [1,1,0,1,1,1,0,1,1,1,1,1,1,1,0,0,1,1]
counting = 0
def maior(lista):
    ans = []
    counting = 0
    for x in nums:
        if x == 1:
            counting+=1
            ans.append(counting)
        if x == 0:
            counting = 0
            ans.append(counting)
    return max(ans)

print(maior(nums))


7


In [15]:
nums = [3, 2 , 4]
target = 6

def twosum(nums: list[int], target: int) -> list[int]:
    value = 0
    ans = []
    for i in range(len(nums)):
        for k in range(len(nums)):
            if i != k:
                value = nums[i] + nums[k]
                if value == target:
                    ans.extend([i, k])
                    return ans

print(twosum(nums, target))
            


[1, 2]
