In [1]:
"""
Este arquivo tem valores ausentes de propósito.

Use df.isna().sum() para localizar os valores ausentes.
Preencha cada valor ausente com a média de sua respectiva coluna.
Converta as três colunas numéricas para uma matriz NumPy.
Calcule a média e o desvio-padrão de cada coluna usando axis=0.
Padronize os dados com (X - media) / desvio.
Confirme se as colunas padronizadas ficaram com média próxima de zero.
Desafio: encontre as linhas nas quais alguma medição padronizada tem valor absoluto maior que 1.5.
"""

'\nEste arquivo tem valores ausentes de propósito.\n\nUse df.isna().sum() para localizar os valores ausentes.\nPreencha cada valor ausente com a média de sua respectiva coluna.\nConverta as três colunas numéricas para uma matriz NumPy.\nCalcule a média e o desvio-padrão de cada coluna usando axis=0.\nPadronize os dados com (X - media) / desvio.\nConfirme se as colunas padronizadas ficaram com média próxima de zero.\nDesafio: encontre as linhas nas quais alguma medição padronizada tem valor absoluto maior que 1.5.\n'

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("exercicios_csv/leituras_sensores.csv")
print(df.shape)
print(df.dtypes)
print(df.head(10))



(10, 4)
horario              str
temperatura_c    float64
umidade_pct      float64
pressao_hpa      float64
dtype: object
  horario  temperatura_c  umidade_pct  pressao_hpa
0   08:00           25.1         71.0       1012.4
1   09:00           25.8         69.5       1012.1
2   10:00           26.7          NaN       1011.8
3   11:00           27.9         64.2       1011.3
4   12:00            NaN         61.8       1010.9
5   13:00           29.4         59.5       1010.5
6   14:00           30.1         58.1          NaN
7   15:00           29.7         59.0       1009.8
8   16:00           28.8         62.3       1010.1
9   17:00           27.4         66.7       1010.7


In [ ]:
colunas = ["temperatura_c", "umidade_pct", "pressao_hpa"]
df[colunas] = df[colunas].fillna(df[colunas].mean())



leituras = df[["temperatura_c", "umidade_pct", "pressao_hpa"]].to_numpy()
media = np.mean(leituras, axis=0)
desvio = np.std(leituras, axis=0)
dados_padronizados = (leituras - media) / desvio

print(dados_padronizados)
print(df.isna().sum())
print(dados_padronizados.mean(axis=0))
mascara = np.any(np.abs(dados_padronizados) > 1.5, axis=1)
print(df.loc[mascara])


[[-1.75417217e+00  1.78880330e+00  1.65890867e+00]
 [-1.31212079e+00  1.42783403e+00  1.28565422e+00]
 [-7.43769001e-01  1.70989398e-15  9.12399770e-01]
 [ 1.40333774e-02  1.52409250e-01  2.90309018e-01]
 [ 2.24354573e-15 -4.25141592e-01 -2.07363584e-01]
 [ 9.61286351e-01 -9.78627816e-01 -7.05036186e-01]
 [ 1.40333774e+00 -1.31553247e+00 -1.41447061e-13]
 [ 1.15073695e+00 -1.09895091e+00 -1.57596324e+00]
 [ 5.82385161e-01 -3.04818500e-01 -1.20270879e+00]
 [-3.01717614e-01  7.54024711e-01 -4.56199885e-01]]
horario          0
temperatura_c    0
umidade_pct      0
pressao_hpa      0
dtype: int64
[ 8.99280650e-16  1.02140518e-15 -2.12119211e-13]
[ True False False False False False False  True False False]
  horario  temperatura_c  umidade_pct  pressao_hpa
0   08:00           25.1         71.0       1012.4
7   15:00           29.7         59.0       1009.8
